// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: no-empty.proto

// fix imports

package example

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NoEmptyService_Get_FullMethodName = "/petstore.NoEmptyService/Get"
)

// NoEmptyServiceClient is the client API for NoEmptyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoEmptyServiceClient interface {
	Get(ctx context.Context, in *NoEmpty, opts ...grpc.CallOption) (*NoEmpty, error)
}

type noEmptyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNoEmptyServiceClient(cc grpc.ClientConnInterface) NoEmptyServiceClient {
	return &noEmptyServiceClient{cc}
}

func (c *noEmptyServiceClient) Get(ctx context.Context, in *NoEmpty, opts ...grpc.CallOption) (*NoEmpty, error) {
	out := new(NoEmpty)
	err := c.cc.Invoke(ctx, NoEmptyService_Get_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoEmptyServiceServer is the server API for NoEmptyService service.
// All implementations must embed UnimplementedNoEmptyServiceServer
// for forward compatibility
type NoEmptyServiceServer interface {
	Get(context.Context, *NoEmpty) (*NoEmpty, error)
	mustEmbedUnimplementedNoEmptyServiceServer()
}

// UnimplementedNoEmptyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNoEmptyServiceServer struct {
}

func (UnimplementedNoEmptyServiceServer) Get(context.Context, *NoEmpty) (*NoEmpty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedNoEmptyServiceServer) mustEmbedUnimplementedNoEmptyServiceServer() {}

// UnsafeNoEmptyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoEmptyServiceServer will
// result in compilation errors.
type UnsafeNoEmptyServiceServer interface {
	mustEmbedUnimplementedNoEmptyServiceServer()
}

func RegisterNoEmptyServiceServer(s grpc.ServiceRegistrar, srv NoEmptyServiceServer) {
	s.RegisterService(&NoEmptyService_ServiceDesc, srv)
}

func _NoEmptyService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoEmptyServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoEmptyService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoEmptyServiceServer).Get(ctx, req.(*NoEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

// NoEmptyService_ServiceDesc is the grpc.ServiceDesc for NoEmptyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoEmptyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "petstore.NoEmptyService",
	HandlerType: (*NoEmptyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _NoEmptyService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "no-empty.proto",
}
