// Code generated by protoc-gen-go-grpc-fixture. DO NOT EDIT.
// source: no-empty.proto

package example

import (
	context "context"
	protoc_gen_go_grpc_fixture "github.com/snarky-puppy/protoc-gen-go-grpc-fixture"
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NoEmptyServiceClient is the fixture stub API for NoEmptyService service.
type noEmptyServiceFixtures struct {
	baseDir string
}

func NewNoEmptyServiceFixtures(baseDir string) NoEmptyServiceClient {
	return &noEmptyServiceFixtures{baseDir: baseDir}
}

func (c *noEmptyServiceFixtures) Get(ctx context.Context, in *NoEmpty, opts ...grpc.CallOption) (*NoEmpty, error) {
	out := new(NoEmpty)
	return protoc_gen_go_grpc_fixture.Fixture(c.baseDir, NoEmptyService_Get_FullMethodName+".json", out)
}
